### ISSUE TITLE
usepiececollisionvolumes = 1, tag hitboxes do not accept AOE damage.

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/spring#1653] opened 2024-08-19 04:02 UTC
all hitboxes generated/enabled with usepiececollisionvolumes = 1 cannot accept aoe damage 
it goes back to the radius of the unit defined in the .s3o

however weapons with the impactonly = 1, tag are unaffected

**Comment by lhog** [comment] 2024-08-19 22:02
Likely a dup of https://github.com/beyond-all-reason/spring/issues/1513
Anyway send the details here or there.

**Comment by drivver44** [comment] 2024-08-19 22:55
I forgot to check if this was a duplicate or not
Please close this one
I’ll add further details on that issue as I’ve isolated the cause on this
issue

**Comment by sprunk** [comment] 2024-08-19 22:56
Apparently a duplicate of #1513.

**Closed by sprunk** 2024-08-19 22:56 UTC
