### ISSUE TITLE
Missing weapontags

### ISSUE THREAD

**Issue by TheSilverHornet** [beyond-all-reason/spring#1084] opened 2023-11-17 13:50 UTC
Looks like fastQueryPointUpdate and fastautoretargeting are undocumented extras also
Will update this if, as & when I find more

**Comment by sprunk** [comment] 2023-11-17 13:58
Duplicate of #1083 which also links to the full list

**Closed by sprunk** 2023-11-17 13:58 UTC

**Comment by TheSilverHornet** [comment] 2023-11-17 14:03
It wasn't a dupe at the time, it came from the same conversation I started. As long as they're known and listed somewhere that's all good.
