### ISSUE TITLE
Add new skidding unitdefs to recoil website

### ISSUE THREAD

**Issue by SethDGamre** [beyond-all-reason/spring#1681] opened 2024-09-16 01:12 UTC
Hi. There's no documentation for the skidding mechanics 

https://beyond-all-reason.github.io/spring/changelogs/changelog-105-2511#skidding Specifically these.

Right now the only way to find them is by knowing what you're looking for and digging through the changelog for something you probably don't know exists.

Thanks.

**Comment by sprunk** [comment] 2024-09-16 01:26
Duplicate of #1087

**Closed by sprunk** 2024-09-16 01:26 UTC
