### ISSUE TITLE
1408 invisible units

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#545] opened 2022-12-11 05:30 UTC
All my units were invisible. They had shadows, could be selected etc. Every unit is drawn "with a shader" in ZK so that outlines work.

Persisted with luaui disable. Luarules reload fixed. Luaui reload then maintained the fix.

[infolog.txt](https://github.com/beyond-all-reason/spring/files/10201527/infolog.txt)

**Comment by GoogleFrog** [comment] 2022-12-11 05:43
Happened again. Seems consistent on planet Walchice.

![Uploading image.png…]()

**Comment by GoogleFrog** [comment] 2022-12-11 05:45
Didn't happen on 105.1.1-1393-gfffa38b

**Comment by lhog** [comment] 2022-12-11 10:18
> planet Walchice.

This tells me nothing. Is the map `Archers_Valley_v6` ?

But I suspect it's related to CUS GL4. I was dealing with similar issue, but only happening with models preload = off. I never found the root cause, except the fact it was caused by CUS GL4 and was only happening in ZK. What if you add all units with `/luarules give all`?

**Comment by GoogleFrog** [comment] 2022-12-13 08:39
[scriptFile.txt](https://github.com/beyond-all-reason/spring/files/10215952/scriptFile.txt)

Here is a script for the planet if you would prefer.

**Comment by Beherith** [comment] 2022-12-16 11:36
[t=00:01:11.078487][f=0000030] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=DrawOpaqueUnitsLua trace=[Internal Lua error: Call failure] [LuaVAOImpl::DrawCheck]: Requested number of elements 2 with offset 0 exceeds buffer size 0
[t=00:01:11.086142][f=0000030] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=DrawOpaqueUnitsLua trace=[Internal Lua error: Call failure] [LuaVAOImpl::DrawCheck]: Requested number of elements 2 with offset 0 exceeds buffer size 0

**Comment by Beherith** [comment] 2022-12-16 11:37
Its a VAO implementation issue @lhog

**Comment by lhog** [comment] 2022-12-16 16:10
Should be fixed in https://github.com/beyond-all-reason/spring/commit/48ebbca6f71479d0d174dac6815f6f8bfae5ab12

**Closed by lhog** 2022-12-16 16:10 UTC
