### ISSUE TITLE
Prone to random stutter, starting at Spring version 105.1.1-1572-g4a16bf2

### ISSUE THREAD

**Issue by completesomething** [beyond-all-reason/spring#679] opened 2023-03-07 04:08 UTC
My ZK engine tests are prone to random stutter, starting at Spring version 105.1.1-1572-g4a16bf2. It doesn't necessarily correlate with beefy commands. CPU/GPU usage doesn't noticeably change. Nothing shows up in the debug log when it happens. Still occurs as of version 1621.

GPU: RX 580
CPU: i5-4690k
OS: Debian sid

**Comment by Beherith** [comment] 2023-03-07 07:32
This is likely due to newer AMD GPU drivers not enjoying the old DisplayList functionality used heavily by this widget.

**Comment by completesomething** [comment] 2023-03-07 07:36
I assume you meant that reply to https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1576 ?

**Comment by Beherith** [comment] 2023-03-07 07:38
Ah yes my bad, ZK is also a heavy user of displaylists (chili)

**Comment by lhog** [comment] 2023-03-07 08:02
@completesomething so I assume `105.1.1-1571-g0fe2b71` is not prone to the stuttering?

**Comment by lhog** [comment] 2023-03-07 08:06
The problem with `1572` is that it got merged with a huge cumulative commit https://github.com/beyond-all-reason/spring/commit/4a16bf204798d78bad876829332bcbafb54c8939

We will probably need to bisect this commit even further to triage which commit from the https://github.com/beyond-all-reason/spring/commits/BAR105-no-vertex-arrays-pt1-redux branch caused it.

**Comment by lhog** [comment] 2023-03-07 16:35
Also please run two similar games on `1572` and `1571` engines enabling `/debuggl 1` in-game and upload two infolog.txt files from these runs respectively.

**Comment by marcushutchings** [comment] 2023-03-08 11:00
Maybe the Tracy tool can help here?

**Comment by lhog** [comment] 2023-03-09 23:26
Preliminary this is very similar to https://github.com/beyond-all-reason/spring/issues/662

ZK has a number of `gl.DrawGroundCircle()` which in turn invokes calls like `glSurfaceCircle` and `glBallisticCircle` implementation of which got upgraded. The problem is that ZK wraps `gl.DrawGroundCircle()` calls into display lists. Apparently this doesn't work well with AMD & Mesa.

**Comment by sprunk** [comment] 2023-03-09 23:31
What can ZK do? Is there some easy GL4 replacement for ground circles?

**Comment by lhog** [comment] 2023-03-09 23:38
The simplest thing to do is to stop wrapping them into DLs, but then you ask the right question as in "how to do it efficiently?"
The simple to say and complex to do method is to use Lua and LuaVAO/LuaVBO to store geometry efficiently, but as noted it's not easy to do.

I'll see what can be done.

**Comment by sprunk** [comment] 2023-03-09 23:50
Perhaps some `gl.GetGroundCircleGeometryInSomeVaoFriendlyFormat()`?

**Comment by lhog** [comment] 2023-03-10 10:41
> Perhaps some `gl.GetGroundCircleGeometryInSomeVaoFriendlyFormat()`?

Yep, potentially in mid-distant future. The problem with functions like above is that the geometry is often not enough. It should be a list of {state, geometry, shader, shader uniforms} tuples. So potentially there will be a need to expose `LuaDrawTask` or something of that sort so Lua side can request, keep and destroy them.

For now I'm gonna see if reverting to old ways for Lua specifically does the trick https://github.com/beyond-all-reason/spring/commit/4439eb606757e18e58f4b9c0a8369ad883d5bc0a

**Comment by lhog** [comment] 2023-03-10 20:42
@completesomething confirmed https://github.com/beyond-all-reason/spring/commit/f038c12e2789ff76314f1fa5976441e5803a5e2d "fixes" the issue (more like works around it).

I'm gonna make a new ticket to track the implementation of a proper way to do things here.

**Closed by lhog** 2023-03-10 20:42 UTC
Labels: bug, Release Blocker

**Comment by Beherith** [comment] 2023-03-10 22:49
Yes, there are multiple minimal examples of doing exactly this. See sensor ranges widgets in bar
