### ISSUE TITLE
105.1.1-941-g941148f turiyag reports terrible FPS that was solved by enabling vsync

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#290] opened 2022-06-01 08:31 UTC
> I have the latest patch on Steam (as of 2022-05-31) and an RTX 3080, this game hasn't been graphically taxing before, but now it is very stuttery. If I stay at a particular zoom level for more than 10 seconds, my FPS drops to around 2-3. Zooming out and then back in, oddly, seems to reset it. How do I go back a couple patches? Is that a thing?

**Comment by GoogleFrog** [comment] 2022-06-01 08:43
> This was resolved by me setting VSync to "Standard".
"Standard" vsync is "VSync = 1" for springsettings.cfg.

**Comment by MaDDoXbr** [comment] 2022-07-13 16:02
I can confirm that. Enabling VSync has fixed low performance for all our players.

**Comment by lhog** [comment] 2022-07-13 17:20
Is this novel? I need someone to bisect the issue with me. If this is new, I have no idea where this might come from.

**Comment by lhog** [comment] 2022-08-10 12:23
`VSync = -1` is now a default. In any cast last bump before I close it, unless someone can debug it with me.

**Comment by sprunk** [comment] 2023-11-18 10:49
Looks like no further complaints and apparently there is a better default now.

**Closed by sprunk** 2023-11-18 10:49 UTC
Labels: bug
