### ISSUE TITLE
Spring.SpawnExplosion inside ProjectileCreated crashes Spring

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#56] opened 2021-07-22 12:37 UTC
Not urgent (neither BAR nor ZK do this, it was discovered by some random modder, and can be worked around).

Here's a snippet to reproduce:
```lua
function gadget:ProjectileCreated()
    -- rule out recursion
    if already then return end
    already = true  

    Spring.SpawnExplosion(100, 100, 100, 1, 1, 1, -- position/direction, dont seem to matter
         {} -- explosion params; the contents don't matter, empty is valid
    )
end
```

Calling it from elsewhere works (checked `gadget:GameFrame`, `script.Shot`, and `script.FireWeapon`).

**Comment by sprunk** [comment] 2021-07-26 15:03
Apparently it can crash in `GameFrame` as well and whether or not it does depends on how the stack looks (adding/removing local vars and lines of code earlier in the function can make it appear seemingly at random).

**Comment by HTMLPhoton** [comment] 2021-07-26 15:08
Here's a gadget to reproduce the crash in `GameFrame`
The most notable part is line 223. which stops the crashing once it is uncommented.
```
function gadget:GetInfo()
	return {
		name      = "Piercing Hitscan Handler",
		desc      = "Makes piercing hitscan a thing",
		author    = "StuffPhoton",
		date      = "9th, June, 2021",
		license   = "CC-BY-SA",
		layer     = 0,
		enabled   = true,
	}
end
--[[

Handled customParams
		piercing_hitscan_spacing
			REQUIRED
			the amount of space between each segment of the beam.
		piercing_hitscan_dynamic_radius_start
			OPTIONAL
			if piercing_hitscan_dynamic_radius_end is also present, the the segment radius would start off at this value (at the start of the barrel)
			NOTE: that this is a multipler, so 100 does not mean 100 elmos of radius, it means 100x the weapon's regular radius!
			if either one is nil, the no dynamic radius happens
			NOTE: VALUES ABOVE 1 WILL BE CLAMPED TO 1 BY SPRING
				(more specifically, any explosions that lua tries to spawn whose passed damage/craterAreaOfEffect is greater than it's weapondef damage/craterAreaOfEffect will have it's damage/craterAreaOfEffect set to it's weapondef value)
		piercing_hitscan_dynamic_radius_end
			OPTIONAL
			if piercing_hitscan_dynamic_radius_start is also present, the the segment radius would end up as this value (at max range)
			NOTE: that this is a multipler, so 100 does not mean 100 elmos of radius, it means 100x the weapon's regular radius!
			if either one is nil, the no dynamic radius happens
			NOTE: VALUES ABOVE 1 WILL BE CLAMPED TO 1 BY SPRING
				(more specifically, any explosions that lua tries to spawn whose passed damage/craterAreaOfEffect is greater than it's weapondef damage/craterAreaOfEffect will have it's damage/craterAreaOfEffect set to it's weapondef value)
		piercing_hitscan_dynamic_radius_exponent
			DEFAULT: 0
			the exponent to raise the "distance" from the origin to
			numbers greater than 1 cause the radius to raise slower near the start and faster near the end
			numbers less than 1 cause the radius to raise faster near the start and slower near the end.
			the effect of any number X is effectively the inverse of the effect of 1/X
			(Negative numbers may cause some funky shit, use at your own risk)
		piercing_hitscan_graphics
			OPTIONAL
			the emitSFX id to call when the projectile is fired for graphics. can be a weapon.
			if nil, then no emitSFX is done
		piercing_hitscan_graphics_velmod
			DEFAULT: 1
			the number to multiply the velocity of the spawned SFX by
			the base velocity is the distance between each segment of the beam, i.e. `piercing_hitscan_spacing`
			this is useful if your spawned SFX behaves differently with a different velocity. namely if it is a `burnblow` or arcing trajectory weapon. NOTE: IF THE RESULTING VELOCITY (THIS TIMES `piercing_hitscan_spacing`) IS GREATER THAN THE WEAPON'S RANGE, SPRING WILL THROW A ACCESS VIOLATION!
		piercing_hitscan_ceg_sizemod
			DEFAULT: 1
			the size modifer of the ceg that is spawned by the explosions
			unsure of actualy effects.
		piercing_hitscan_hitunit_checkradius
			DEFAULT: damageAreaOfEffect
			the radius to check for units when spawning an explosion. if the unit exsit, then the unit's `unitID` is passed to `Spring.SpawnExplosion`
			if zero or lower, then the check is skipped
		piercing_hitscan_hitfeature_checkradius
			DEFAULT: damageAreaOfEffect
			the radius to check for features when spawning an explosion. if the feature exsit, then the feature's `featureID` is passed to `Spring.SpawnExplosion`
			if zero or lower, then the check is skipped
		piercing_hitscan_cycleSpeed
			OPTIONAL
			the speed, in fraction of the spacing, that each segment "moves" per frame
			used to create a traditional tractor beam effect
			if nil, the none of this happens
]]--

if not gadgetHandler:IsSyncedCode() then -- this only exsits in synced luarules
	return
end

Spring.Echo("PHH Synced: Started Loading...") --the shortname might make it seem like this gadget exsits in both synced and unsynced luarules...

local spGetProjectilePosition = Spring.GetProjectilePosition
local spGetProjectileVelocity = Spring.GetProjectileVelocity
local spSpawnExplosion = Spring.SpawnExplosion
local spGetGameFrame = Spring.GetGameFrame
local spGetUnitsInSphere = Spring.GetUnitsInSphere
local spGetFeaturesInSphere = Spring.GetFeaturesInSphere
local spSpawnSFX = Spring.SpawnSFX
local spDeleteProjectile = Spring.DeleteProjectile
local spGetProjectileDefID = Spring.GetProjectileDefID
local spEcho = Spring.Echo

local sqrt = math.sqrt
local atan2 = math.atan2

local debug = false
local spamInfologs = false --and when I say this will spam the infologs, I mean it!
--you're gonna be printing HUNDREDS OF KILOBYTES of text!

local handledWeapons = {}

local queuedBeams = {} --you can't spawn explosions in ProjectileCreated. springweirdman

for i=1, #WeaponDefs do
	local wd = WeaponDefs[i]
	local cp = wd.customParams
	if cp.piercing_hitscan_spacing then -- customParams is never nil. weapondefs_post made sure of that
		handledWeapons[i] = {}
		handledWeapons[i]["spacing"] = tonumber(cp.piercing_hitscan_spacing)
		handledWeapons[i]["explosionCount"] = wd.range / handledWeapons[i]["spacing"]
		handledWeapons[i]["sfx"] = tonumber(cp.piercing_hitscan_graphics)
		handledWeapons[i]["sfxVelMod"] = tonumber(cp.piercing_hitscan_graphics_velmod) or 10
		handledWeapons[i]["gfxMod"] = tonumber(cp.piercing_hitscan_ceg_sizemod) or 1
		handledWeapons[i]["cycleSpeed"] = tonumber(cp.piercing_hitscan_cycleSpeed)
		
		handledWeapons[i]["damages"] = {}
		for n=0, 4 do
			handledWeapons[i]["damages"][n] = wd.damages[n]
		end
		
		if cp.piercing_hitscan_dynamic_radius_start and cp.piercing_hitscan_dynamic_radius_end then
			handledWeapons[i]["dynamicRadiusMin"] = tonumber(cp.piercing_hitscan_dynamic_radius_start)
			handledWeapons[i]["dynamicRadiusAdd"] = tonumber(cp.piercing_hitscan_dynamic_radius_end) - tonumber(cp.piercing_hitscan_dynamic_radius_start) --can result in a neagtive number, which is perfectly fine
			handledWeapons[i]["dynamicRadiusExponent"] = tonumber(cp.piercing_hitscan_dynamic_radius_exponent)
		end
		
		handledWeapons[i]["unitCheckRadius"] = tonumber(cp.piercing_hitscan_hitunit_checkradius) or wd.craterAreaOfEffect
		handledWeapons[i]["featureCheckRadius"] = tonumber(cp.piercing_hitscan_hitunit_checkradius) or wd.craterAreaOfEffect
		
		if handledWeapons[i]["explosionCount"] % 1 ~= 0 then
			spEcho("PHH Synced: the weapon " .. wd.name .. " has a range of " .. wd.range .. " but would actually be " .. math.floor(handledWeapons[i]["explosionCount"]) * handledWeapons[i]["spacing"] .. " ingame! Please either:\n - set range to " .. math.floor(handledWeapons[i]["explosionCount"]) * handledWeapons[i]["spacing"] .. " (no logic change)\n - set range to " .. math.ceil(handledWeapons[i]["explosionCount"]) * handledWeapons[i]["spacing"] .. " (next available breakpoint)\n - set weaponVelocity to " .. wd.range / math.floor(wd.range / handledWeapons[i]["spacing"]) .. " (to keep current range)")
		end
		
		if true then
			--Spring.Echo("HPH Synced: Processed weapondef ID:" .. i)
			--Spring.Echo(Spring.Utilities.TableToString(handledWeapons[i]))
			---spEcho("PHH Synced: About to spawn explosions with the following params: " .. Spring.Utilities.TableToString(handledWeapons[i]))
		end
	end
end

function gadget:ProjectileCreated(proID, proOwnerID, weaponDefID)
	weaponDefID = weaponDefID or spGetProjectileDefID(proID)
	if handledWeapons[weaponDefID] then
		queuedBeams[#queuedBeams+1] = {
			proID = proID,
			proOwnerID = proOwnerID,
			weaponDefID = weaponDefID,
		}
	end
end

function gadget:GameFrame(frame)
	for i=1, #queuedBeams do
		local proID = queuedBeams[i]["proID"]
		local proOwnerID = queuedBeams[i]["proOwnerID"]
		local weaponDefID = queuedBeams[i]["weaponDefID"]
		
		local def = handledWeapons[weaponDefID]
		local wd = WeaponDefs[weaponDefID]
		
		if true then
			spEcho("PHH Synced: Spawning beam for weaponDefID: " .. weaponDefID)
		end
		
		local px, py, pz = spGetProjectilePosition(proID)
		local dx, dy, dz = spGetProjectileVelocity(proID)
		local projSpeed = sqrt(dx*dx + dy*dy + dz*dz)
		local vx, vy, vz = dx/projSpeed*def.spacing, dy/projSpeed*def.spacing, dz/projSpeed*def.spacing
		
		local offset = 0
		if def.cycleSpeed then
			offset = (spGetGameFrame() * def.cycleSpeed) % 1
		end
				
		if def.sfx then
			--copypaste of CAS code. it works.
			local vx2 = vx * vx	
			local vy2 = vy * vy
			local vz2 = vz * vz
			local dirX = atan2(vx, sqrt(vy2 + vz2))
			local dirY = atan2(vy, sqrt(vx2 + vz2))
			local dirZ = atan2(vz, sqrt(vx2 + vy2))
			spSpawnSFX(proOwnerID, def.sfx, px, py, pz, dirX, dirY, dirZ)
		end
		
		local radiusMod
		local craterAreaOfEffect = wd.craterAreaOfEffect
		local damageAreaOfEffect = wd.damageAreaOfEffect
		
		local explosionArray = {
		}
		--[[
			damages = def.damages,
			weaponDef = weaponDefID,
			owner = proOwnerID,
			craterAreaOfEffect = craterAreaOfEffect,
			damageAreaOfEffect = damageAreaOfEffect,
			edgeEffectiveness = wd.edgeEffectiveness,
			explosionSpeed = wd.explosionSpeed,
			gfxMod = def.gfxMod,
			impactOnly = false,
			ignoreOwner = wd.noSelfDamage,
			damageGround = ((wd.damages.craterMult and true) or false),
			projectileID = proID,
		]]--
		
		
		explosionArray.damages = def.damages
		explosionArray.weaponDef = weaponDefID
		explosionArray.owner = proOwnerID
		explosionArray.craterAreaOfEffect = craterAreaOfEffect
		explosionArray.damageAreaOfEffect = damageAreaOfEffect
		explosionArray.edgeEffectiveness = wd.edgeEffectiveness
		explosionArray.explosionSpeed = wd.explosionSpeed
		explosionArray.gfxMod = def.gfxMod
		explosionArray.impactOnly = false
		explosionArray.ignoreOwner = wd.noSelfDamage
		explosionArray.damageGround = ((wd.damages.craterMult and true) or false)
		explosionArray.projectileID = proID
		--[[
		--this does cause a crash
		Spring.Utilities.TableToString(explosionArray)
		]]--
		
		--[[
		--this does cause a crash
		local offeringToTheMachineSpirit = "PHH Synced: About to spawn explosions with the following params: " .. Spring.Utilities.TableToString(explosionArray)
		]]--
		
		--[[
		--this does *not* cause a crash
		spEcho("PHH Synced: About to spawn explosions with the following params: " .. Spring.Utilities.TableToString(explosionArray))
		]]--
		
		--[[
		--this does cause a crash
		spEcho(Spring.Utilities.TableToString(explosionArray))
		]]--
		
		--[[
		--this does cause a crash
		if true then
			--Spring.Utilities.TableToString(explosionArray)
		end
		]]--
		
		for i=1, def.explosionCount do
			local x, y, z = vx*(i+offset)+px, vy*(i+offset)+py, vz*(i+offset)+pz
			
			if def.dynamicRadiusMin then
				radiusMod = def.dynamicRadiusMin + def.dynamicRadiusAdd * (i / def.explosionCount) ^ def.dynamicRadiusExponent
				explosionArray.craterAreaOfEffect = craterAreaOfEffect * radiusMod
				explosionArray.damageAreaOfEffect = damageAreaOfEffect * radiusMod
			end
			
			--[[
			local nearbyUnits = spGetUnitsInSphere(x, y, z, def.unitCheckRadius)
			if #nearbyUnits > 0 and nearbyUnits[1] ~= proOwnerID then
				explosionArray["hitUnit"] = nearbyUnits[1]
			elseif #nearbyUnits > 1 then
				explosionArray["hitUnit"] = nearbyUnits[2]
			end
			]]--
			
			if spamInfologs then
				Spring.Echo("PHH Synced: Spawning Explosion at (" .. x .. ", " .. y .. ", " .. z .. ") with a direction of (" .. dx .. ", " .. dy .. ", ".. dz .. ") as part " .. i .. " of the beam")
			end
			spSpawnExplosion(x, y, z, dx, dy, dz, explosionArray)
		end
		
		spDeleteProjectile(proID) --yeet
	end
	
	queuedBeams = {}
end

Spring.Echo("HPH Synced: Finsihed Loading...")
```

**Comment by lhog** [comment] 2021-07-26 15:39
@HTMLPhoton I'm willing to take a look into it. I understand it's ZK or one of its mutators. Would it be possible for you to send me a link to repo / commit so I can reproduce it without the need to integrate the gadget, etc.

**Comment by HTMLPhoton** [comment] 2021-07-26 16:18
@lhog Unfortunately I've done this off-line so there it isn't uploaded to anywhere. I've not very familiar with github and I am keep getting a "Is not included in the list" Error when I try to upload a zipped copy of my working directory.
Here's my unitdefs if this will help
```
return { striderscorpion = {
  unitname               = [[striderscorpion]],
  name                   = [[Scorpion]],
  description            = [[Cloaked Infiltration Strider]],
  acceleration           = 0.78,
  brakeRate              = 4.68,
  buildCostMetal         = 3000,
  builder                = false,
  buildPic               = [[striderscorpion.png]],
  canGuard               = true,
  canManualFire          = true,
  canMove                = true,
  canPatrol              = true,
  category               = [[LAND]],
  cloakCost              = 2,
  cloakCostMoving        = 10,
  collisionVolumeOffsets        = [[0 8 0]],
  collisionVolumeScales         = [[60 20 80]],
  collisionVolumeType           = [[box]],
  selectionVolumeOffsets = [[0 0 0]],
  selectionVolumeScales  = [[85 85 85]],
  selectionVolumeType    = [[ellipsoid]],
  corpse                 = [[DEAD]],

  customParams           = {
    bait_level_default = 0,
    aimposoffset          = [[0 10 0]],
    decloak_footprint     = 5,
  },

  explodeAs              = [[CRAWL_BLASTSML]],
  footprintX             = 4,
  footprintZ             = 4,
  iconType               = [[t3spidergeneric]],
  idleAutoHeal           = 5,
  idleTime               = 1800,
  initCloaked            = true,
  leaveTracks            = true,
  maxDamage              = 12000,
  maxSlope               = 72,
  maxVelocity            = 1.3,
  maxWaterDepth          = 22,
  minCloakDistance       = 150,
  movementClass          = [[TKBOT4]],
  noAutoFire             = false,
  noChaseCategory        = [[TERRAFORM FIXEDWING SATELLITE SUB DRONE]],
  objectName             = [[scorpion.s3o]],
  script                 = [[striderscorpion.lua]],
  selfDestructAs         = [[CRAWL_BLASTSML]],

  sfxtypes               = {

    explosiongenerators = {
      [[custom:zeusmuzzle]],
      [[custom:zeusgroundflash]],
      [[custom:YELLOW_LIGHTNING_MUZZLE]],
      [[custom:YELLOW_LIGHTNING_GROUNDFLASH]],
    },

  },
  sightDistance          = 517,
  trackOffset            = 0,
  trackStrength          = 10,
  trackStretch           = 1,
  trackType              = [[crossFoot]],
  trackWidth             = 76,
  turnRate               = 480,
  workerTime             = 0,

  weapons                = {

    {
      def                = [[FAKELASER]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 30,
    },
    
    {
      def                = [[LGBTIQAPLUSLAZER]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

    {
      def                = [[MULTILIGHTNING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
    },
    
    {
      def                = [[PARTICLEBEAM]],
      mainDir            = [[-0.2 0 1]],
      maxAngleDif        = 240,
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
    },
    
    {
      def                = [[PARTICLEBEAM]],
      mainDir            = [[0.2 0 1]],
      maxAngleDif        = 240,
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
    },
    
  },


  weaponDefs             = {
    
    FAKELASER     = {
      name                    = [[Fake Laser]],
      areaOfEffect            = 12,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      customParams            = {
        bogus = 1,
        reaim_time = 1,
      },

      damage                  = {
        default = 0,
      },

      duration                = 0.1,
      edgeEffectiveness       = 0.99,
      explosionGenerator      = [[custom:flash1green]],
      fireStarter             = 70,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 5.53,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 450,
      reloadtime              = 0.1,
      rgbColor                = [[0 1 0]],
      soundStart              = [[weapon/laser/laser_burn5]],
      soundTrigger            = true,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 5.53,
      tolerance               = 10000,
      turret                  = false,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 900,
    },
    
    LGBTIQAPLUSLAZER = {
      name                    = [[Spectrum Annihilator]],
      areaOfEffect            = 32,
      burst                   = 60,
      burstRate               = 0.066,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      customParams            = {
        light_camera_height = 2000,
        light_color = [[0.3 0.3 0.05]],
        light_radius = 120,
      },

      damage                  = {
        default = 23,
      },
	  
	  customParams            = {
		piercing_hitscan_spacing = 16,
		piercing_hitscan_graphics = 2051,
	  },

      duration                = 0.02,
      explosionGenerator      = [[custom:NONE]],
      fireStarter             = 50,
      impactOnly              = false,
      heightMod               = 1,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 0,
	  leadLimit               = 1,
	  noExplode               = true,
      range                   = 550,
      reloadtime              = 7,
      rgbColor                = [[1 1 0]],
      soundHit                = [[impacts/shotgun_impactv5]],
      soundStart              = [[weapon/shotgun_firev4]],
      soundStartVolume        = 0.5,
      soundTrigger            = true,
      sprayangle              = 0,
      thickness               = 2,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 30,
    },
    
    MULTILIGHTNING = {
      name                    = [[Multi-Stunner]],
      areaOfEffect            = 160,
      avoidFeature            = false,
      burst                   = 20,
      burstRate               = 0.1,
      commandFire             = true,
      craterBoost             = 0,
      craterMult              = 0,
      cylinderTargeting      = 0,

      customParams            = {
        light_color = [[0.7 0.7 0.2]],
        light_radius = 320,
        gui_draw_range = 450,
        reaim_time = 1,
      },

      damage                  = {
        default        = 1001,
      },

      duration                = 8,
      dynDamageExp            = 0,
      edgeEffectiveness       = 0.8,
      explosionGenerator      = [[custom:YELLOW_LIGHTNINGPLOSION]],
      fireStarter             = 0,
      impulseBoost            = 0,
      impulseFactor           = 0,
      intensity               = 12,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      paralyzer               = true,
      paralyzeTime            = 3,
      range                   = 490,
      reloadtime              = 30,
      rgbColor                = [[1 1 0.25]],
      soundStart              = [[weapon/lightning_fire]],
      soundTrigger            = false,
      sprayAngle              = 2048,
      texture1                = [[lightning]],
      thickness               = 10,
      turret                  = true,
      weaponType              = [[LightningCannon]],
      weaponVelocity          = 450,
    },

    PARTICLEBEAM = {
      name                    = [[Auto Particle Beam]],
      beamDecay               = 0.85,
      beamTime                = 1/30,
      beamttl                 = 45,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,
      
      customParams            = {
        light_color = [[0.9 0.22 0.22]],
        light_radius = 80,
        reaim_time = 1,
      },
      
      damage                  = {
        default = 70.01,
      },

      explosionGenerator      = [[custom:flash1red]],
      fireStarter             = 100,
      impactOnly              = true,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      laserFlareSize          = 7.5,
      minIntensity            = 1,
      range                   = 575,
      reloadtime              = 0.3 + 1/30,
      rgbColor                = [[1 0 0]],
      soundStart              = [[weapon/laser/mini_laser]],
      soundStartVolume        = 6,
      thickness               = 5,
      tolerance               = 8192,
      turret                  = true,
      weaponType              = [[BeamLaser]],
    },
  },


  featureDefs            = {

    DEAD  = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 2,
      footprintZ       = 2,
      collisionVolumeOffsets        = [[0 -5 0]],
      collisionVolumeScales         = [[60 20 80]],
      collisionVolumeType           = [[box]],
      object           = [[scorpion_dead.s3o]],
    },
    HEAP  = {
      blocking         = false,
      footprintX       = 2,
      footprintZ       = 2,
      object           = [[debris4x4a.s3o]],
    },

  },

} }
```

**Comment by lhog** [comment] 2021-07-26 16:21
ok, so latest ZK as base + your gadget (un-comment faulty lines) + Scorpion. Is this all I need?

**Comment by lhog** [comment] 2021-07-26 20:35
Also FYI: `Spring.Utilities.TableToString()` is not an engine thing, but rather ZK's one https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Utilities/tablefunctions.lua#L69

**Comment by lhog** [comment] 2021-07-28 17:08
@HTMLPhoton have you figured what is so it in the table so `Spring.Utilities.TableToString()` fails?

**Comment by WatchTheFort** [comment] 2021-07-28 19:31
If the bug is in `Spring.Utilities`, this issue should be moved to the BAR repo, since Spring.Utilities is purely Lua side

**Comment by sprunk** [comment] 2021-07-28 21:00
The way I understood it was that `Spring.Utilities.TableToString` doesn't fail, rather, _adding it_ makes the bug seemingly go away. My snippet with just `SpawnExplosion` inside `ProjectileCreated` reproduces the crash without involving `Spring.Utilities.TableToString` at all.

**Comment by HTMLPhoton** [comment] 2021-07-29 02:22
@lhog what Sprung said is correct. Spring.Utilities.TableToString() doesn't fail. rather, adding it in a **very** specific way makes the bug stop. the widget reliably crashes without it.

**Comment by lhog** [comment] 2021-07-30 18:32
I traced @sprunk first example and I think it deals with the fact that creation of projectile object is not yet complete. Such calls can be blocked (code is done).

But I understand there's also a case when `SpawnExplosion` fails outside of `ProjectileCreated`. Have I got it right?

**Comment by sprunk** [comment] 2021-07-30 18:56
> I think it deals with the fact that creation of projectile object is not yet complete.

This would be very strange because my example doesn't use the projectile being created in any way. Note that it's
```
function gadget:ProjectileCreated()
    ...
    Spring.SpawnExplosion(..., {})
```
and not:
```
function gadget:ProjectileCreated(projID)
    ...
    Spring.SpawnExplosion(..., {projectileID = projID})
```

If it is truly the case that the "fetus" projectile is still somehow referenced then I think the `ProjectileCreated` event should be moved further, to a point where it has actually been fully created. But yes, apparently it's not limited to `ProjectileCreated` in which case this might be moot:

> I understand there's also a case when SpawnExplosion fails outside of ProjectileCreated. Have I got it right?

This is supposed to be @HTMLPhoton 's example. I haven't checked that one yet but I'll try to make a minimal gadget that reproduces it without all the chaff on the weekend if this one is not convenient to work with.

**Comment by lhog** [comment] 2021-07-30 19:47
Yes, confirmed, the projectile is not fully constructed when `ProjectileCreated` is called. And by that I mean the original projectile, the reason of `ProjectileCreated` call.

![image](https://user-images.githubusercontent.com/1476261/127704300-feefc2d8-f802-4828-9b93-c56621ebfb1b.png)

See it's called in inside the constructor of base class and extended properties which `SpawnExplosion()` happens to rely on are not available yet.

**Comment by lhog** [comment] 2021-07-30 20:03
Though I probably worked it around: https://github.com/beyond-all-reason/spring/tree/BAR-fix56

**Comment by HTMLPhoton** [comment] 2021-08-05 10:27
Sorry for the late response, but here's a version of the gadget without all the unneeded chaff. It triggers the `GameFrame` crash when any unit fires it's weapon.

```
function gadget:GetInfo()
	return {
		name      = "Crash Generator",
		desc      = "Creates an Acess Violation via Spring.SpawnExplosion",
		author    = "StuffPhoton",
		date      = "5th, August, 2021",
		license   = "CC-BY-SA",
		layer     = 0,
		enabled   = true,
	}
end

if not gadgetHandler:IsSyncedCode() then -- this only exsits in synced luarules
	return
end

local spGetProjectilePosition = Spring.GetProjectilePosition
local spGetProjectileVelocity = Spring.GetProjectileVelocity
local spSpawnExplosion = Spring.SpawnExplosion
local spGetGameFrame = Spring.GetGameFrame
local spSpawnSFX = Spring.SpawnSFX
local spDeleteProjectile = Spring.DeleteProjectile
local spGetProjectileDefID = Spring.GetProjectileDefID
local spEcho = Spring.Echo

local sqrt = math.sqrt
local atan2 = math.atan2

local queuedBeams = {}

spEcho("weapon_crash.lua has loaded")

function gadget:ProjectileCreated(proID, proOwnerID, weaponDefID)
	weaponDefID = weaponDefID or spGetProjectileDefID(proID)
	queuedBeams[#queuedBeams+1] = {
		proID = proID,
		proOwnerID = proOwnerID,
		weaponDefID = weaponDefID,
	}
	spEcho("WCL Spawning Explosion")
end

function gadget:GameFrame(frame)
	for i=1, #queuedBeams do
		local proID = queuedBeams[i]["proID"]
		local proOwnerID = queuedBeams[i]["proOwnerID"]
		local weaponDefID = queuedBeams[i]["weaponDefID"]
		
		local wd = WeaponDefs[weaponDefID]
		local px, py, pz = spGetProjectilePosition(proID)
		local dx, dy, dz = spGetProjectileVelocity(proID)
		
		local explosionArray = {
			damages = wd.damages,
			weaponDef = weaponDefID,
			owner = proOwnerID,
			craterAreaOfEffect = wd.craterAreaOfEffect,
			damageAreaOfEffect = wd.damageAreaOfEffect,
			edgeEffectiveness = wd.edgeEffectiveness,
			explosionSpeed = wd.explosionSpeed,
			gfxMod = 1,
			impactOnly = false,
			ignoreOwner = wd.noSelfDamage,
			damageGround = ((wd.damages.craterMult and true) or false),
			projectileID = proID,
		}
		
		--this stops the crash
		--spEcho("PHH Synced: About to spawn explosions with the following params: " .. Spring.Utilities.TableToString(explosionArray))
		
		--[[
		--these all do not stop the crash
		if true then
			--Spring.Utilities.TableToString(explosionArray)
		end
		
		spEcho(Spring.Utilities.TableToString(explosionArray))
		
		local offeringToTheMachineSpirit = "PHH Synced: About to spawn explosions with the following params: " .. Spring.Utilities.TableToString(explosionArray)
		
		Spring.Utilities.TableToString(explosionArray)
		]]--
		spSpawnExplosion(px, py, pz, dx, dy, dz, explosionArray)
		
		spDeleteProjectile(proID) --yeet
	end
	
	queuedBeams = {}
end
```

**Comment by lhog** [comment] 2021-08-05 16:54
Yeah Spring.SpawnExplosion() didn't work, `damages` tables was processed incorrectly (wrong Lua stack index). Fixed now.

**Comment by sprunk** [comment] 2021-08-05 17:25
So there were two separate issues (virtual function + incorrect stack index)? Brutal.

**Comment by lhog** [comment] 2021-08-05 19:16
Yeah, the last one was rather tricky as it didn't trigger under MSVC debug mode.

**Closed** 2021-09-16 20:51 UTC
Labels: fixed

**Comment by Anarchid** [comment] 2023-12-03 16:06
Creating a CEG named `custom:none` workarounds this, so it looks like there's a bit too much custom: going on.

**Comment by Anarchid** [comment] 2023-12-03 16:50
I pulled zk master, made a minor change to a ceg, and hit `/reloadcegs`. 

Then i reset --hard to HEAD and tried it again, and it crashed with no local changes, again.

Then i wrote the comment above, and added the custom:custom:none, and it went away.

**Comment by sprunk** [comment] 2023-12-03 18:13
Works for me (windows, map: duck, engine 2110ish)

**Comment by Anarchid** [comment] 2023-12-03 21:59
I don't know what could be interesting, but here's what i get when i do `gdb ./spring` -> `run` and trigger the crash:

```
[t=00:02:14.339488][f=0000660] [ReloadGenerators][generatorID=56] reloading CEG "custom:custom:none"
[t=00:02:14.339491][f=0000660] Warning: [CCEG::Load] table for CEG "custom:none" invalid (parse errors?)

Thread 1 "spring-main" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
76	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
```
