### ISSUE TITLE
FPS deterioration happened between 1103 and 1105

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#412] opened 2022-09-23 15:48 UTC
![screen00135](https://user-images.githubusercontent.com/89547444/192509018-ba60519a-29f6-4b9e-9f3b-50f70abb3643.jpg)
![screen00136](https://user-images.githubusercontent.com/89547444/192509027-b56dd069-ac09-4bd2-9eab-8797878da2fa.jpg)

**Comment by lhog** [comment] 2022-09-23 18:25
We need more data points from someone else because I can't reproduce it.
![screen00035](https://user-images.githubusercontent.com/1476261/192032834-a367a73f-a088-4528-a08c-e35310010762.jpg)
![screen00036](https://user-images.githubusercontent.com/1476261/192032843-492322e8-7baa-45a7-8e2a-2c0ab5f5276d.jpg)

**Comment by lhog** [comment] 2022-09-27 10:20
Fixed via https://github.com/beyond-all-reason/spring/commit/d9b7618674825db72484a893087ea583ec74dbbd

**Comment by lhog** [comment] 2022-09-28 07:19
Yep, it's the commit I enabled colored shadows: https://github.com/beyond-all-reason/spring/commit/8517d442b5157deb636c152e541ddfb44debef5c
Making it conditional is too much hassle, although some performance (and most importantly VRAM occupation) improvements are possible.

**Closed** 2022-09-28 07:20 UTC
