### ISSUE TITLE
shadows dissapear when the camera is too close to the ground

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/spring#242] opened 2022-03-28 07:05 UTC
![screen00066](https://user-images.githubusercontent.com/75929927/160344055-fe87962f-2bce-42c0-b872-eaaa4f403869.jpg)
![screen00067](https://user-images.githubusercontent.com/75929927/160344059-072c62c3-b807-475c-be63-7496148d59d7.jpg)

**Comment by Beherith** [comment] 2022-03-28 07:34
Duplicate of #83

**Closed** 2022-07-29 01:13 UTC
